---
#php 5.3

- hosts: web
  vars:
     src_dir: /usr/src/ansible

     php_old_dir: /shared/php-5.3.28
     php_old_version: 5.3.28

     php_dir: /shared
     php_version: 5.3.29
     mysql_version: 5.6.29
     pg_version: 9.5.2
     apache_version: 2.4.18
     libpng_version: 1.6.21
     libjpeg_version: 6b

     update_libpng: false
     update_libjpeg: false
     update_mysql: false
     update_postgresql: false
     update_imap: false
     update_php: true

  pre_tasks:
  - name: make dir
    file: path={{ item }} state=directory
    with_items:
    - "{{ src_dir }}"
  - stat: path=/usr/local/libjpeg-{{ libjpeg_version }}
    register: libjpeg
  - name: Libjpeg
    include: ../include/libjpeg.yml
    when: libjpeg.stat.isdir is not defined or update_libjpeg

  - stat: path=/usr/local/libpng-{{ libpng_version }}
    register: libpng
  - name: Libpng
    include: ../include/libpng.yml
    when: libpng.stat.isdir is not defined or update_libpng

  - stat: path=/usr/local/mysql-{{ mysql_version }}
    register: mysql
  - name: Mysql
    include: ../include/mysql.yml
    when: mysql.stat.isdir is not defined or update_mysql

  - stat: path=/usr/local/postgresql-{{ pg_version }}
    register: pg
  - name: Pg
    include: ../include/postgresql.yml
    when: pg.stat.isdir is not defined or update_postgresql

  - stat: path=/usr/local/imap-2007f
    register: imap
  - name: IMAP
    include: ../include/imap.yml
    when: imap.stat.isdir is not defined or update_imap

  - name: Install depedences
    yum: name={{ item }} state=latest
    with_items:
    - libxml2-devel
    - libcurl-devel
    - freetype-devel
    - freetype
    - libmcrypt-devel
    - libtidy-devel
    - libxslt-devel
    - php-mbstring
    - libtool-ltdl-devel
    - libc-client-devel

  tasks:

  - action: shell date '+%Fa'
    register: mydate

  - block:
    - name: php53
      get_url: url={{ item }}  dest={{ src_dir }}
      with_items:
      - http://pl1.php.net/get/php-5.3.29.tar.gz/from/this/mirror

    - name: Unarchive apache
      unarchive: src={{ src_dir }}/{{ item }}  dest={{ src_dir }} copy=no
      with_items:
      - php-{{ php_version }}.tar.gz

    - name: Copy go.sh file
      copy: src={{ item.src }} dest={{ item.dest }} mode="755"
      with_items:
      - { src: ../scripts/go-5.3.sh, dest: "{{ src_dir }}/php-{{ php_version }}/go.sh" }

    - name: Add line
      replace: dest={{ item.dest }} regexp={{ item.regexp }} replace={{ item.replace }}
      with_items:
      - { dest: "{{ src_dir }}/php-{{ php_version }}/go.sh", regexp: MYSQL_VERSION, replace: "{{ mysql_version }}" }
      - { dest: "{{ src_dir }}/php-{{ php_version }}/go.sh", regexp: PG_VERSION, replace: "{{ pg_version }}" }
      - { dest: "{{ src_dir }}/php-{{ php_version }}/go.sh", regexp: LIBPNG_VERSION, replace: "{{ libpng_version }}" }
      - { dest: "{{ src_dir }}/php-{{ php_version }}/go.sh", regexp: LIBJPEG_VERSION, replace: "{{ libjpeg_version }}" }
      - { dest: "{{ src_dir }}/php-{{ php_version }}/go.sh", regexp: DATE, replace: "{{ mydate.stdout }}" }
      - { dest: "{{ src_dir }}/php-{{ php_version }}/go.sh", regexp: PHP_DIR, replace: "{{ php_dir }}" }
      - { dest: "{{ src_dir }}/php-{{ php_version }}/go.sh", regexp: PHP_VERSION, replace: "{{ php_version }}" }



    - stat: path=/usr/local/php-{{ php_version }}
      register: php52
    - name: Installing
      shell:  chdir="{{ src_dir }}/php-{{ php_version }}" {{ item }}
      with_items:
      - ./go.sh &> /dev/null
      - make  &> /dev/null
      - make install  &> /dev/null
      when: php52.stat.isdir is not defined or update_php

    - name: Sync
      synchronize:
       src: "{{ php_old_dir }}/"
       dest: "{{ php_dir }}/php-{{ php_version }}-{{ mydate.stdout }}"
       rsync_opts: --ignore-existing
      delegate_to: "{{ inventory_hostname }}"

    - name: Add line 2
      replace: dest={{ item.dest }} regexp={{ item.regexp }} replace={{ item.replace }}
      with_items:
        - {
          dest: "{{ php_dir }}/php-{{ php_version }}-{{ mydate.stdout }}/php.ini",
          regexp: "{{ php_old_version }}",
          replace: "{{ php_version }}-{{ mydate.stdout }}"
        }

    - name: Rename module
      command: mv /usr/local/apache2/modules/libphp5.so /usr/local/apache2/modules/libphp{{ php_version }}-{{ mydate.stdout }}.so

    - name: apachectl
      shell: cp /usr/local/apache2/bin/apachectl-{{ php_old_version }} /usr/local/apache2/bin/apachectl-{{ php_version }}-{{ mydate.stdout }}

    - name: Change
      replace: dest="/usr/local/apache2/bin/apachectl-{{ php_version }}-{{ mydate.stdout }}" regexp="{{ php_old_version }}" replace="{{ php_version }}-{{ mydate.stdout }}"

    - name: PHP link
      file: src=/shared/php-{{ php_version }}-{{ mydate.stdout }} dest=/usr/local/php-{{ php_version }}-{{ mydate.stdout }} state=link

    - name: Apache link
      file: src=/usr/local/apache2/bin/httpd dest=/usr/local/apache2/bin/httpd-{{ php_version }}-{{ mydate.stdout }} state=link

    - name: Apache conf
      shell: cp /usr/local/apache2/conf/httpd-{{ php_old_version }}.conf /usr/local/apache2/conf/httpd-{{ php_version }}-{{ mydate.stdout }}.conf

    - name: Add line 2
      replace: dest={{ item.dest }} regexp={{ item.regexp }} replace={{ item.replace }}
      with_items:
        - {
          dest: "/usr/local/apache2/conf/httpd-{{ php_version }}-{{ mydate.stdout }}.conf",
          regexp: "{{ php_old_version }}",
          replace: "{{ php_version }}-{{ mydate.stdout }}"
        }
    - name: Change supervisor.conf
      replace: dest=/etc/supervisord.conf regexp="httpd-{{ php_old_version }}" replace="httpd-{{ php_version }}-{{ mydate.stdout }}"

    when: update_php
